# instrucciones para la BD en Docker

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dlt_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  #carpeta donde se guarda por si acaso
  postgres_data: